config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
  belongs_to :location

  validates :start_date, presence: true, uniqueness: { scope: :car, message: "Dates Unavailable" }
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates  :color, presence: true
  validates  :brand, presence: true
  validates  :model, presence: true
  validates  :fuel_type, presence: true
  # validates  :bluetooth, inclusion: { in: [true, false] }
  # validates  :automatic, inclusion: { in: [true, false] }
  validates  :price_per_day, presence: true
  validates  :seats, presence: true
  validates :seats, numericality: { only_integer: true }
  has_many_attached :photos
  include PgSearch::Model
  pg_search_scope :search_by_brand_and_model,
  against: [ :brand, :model, :color, :fuel_type ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :cars
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    if @booking.save
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :location_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      @cars = Car.search_by_brand_and_model(params[:query])
    else
      @cars = Car.all
    end
  end

  def show
    @cars = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :color, :fuel_type, :price_per_day, :automatic, :bluetooth, :seats, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @locations = Location.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude
      }
    end
  end

  def dashboard
    @bookings = current_user.bookings
    @usercars = current_user.cars
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <h1>Edit Booking</h1>
  <%= simple_form_for(@booking) do |f| %>
    <div data-controller='date-picker'>

      <div class='mb-3 string required booking_start_date'>
        <label class='form-label string required' for='dateRange'>Select Date</label>
        <input class='form-control string required' placeholder="<%= @booking.start_date.strftime("%m/%d/%Y - %R") %>% to <%= @booking.end_date.strftime("%m/%d/%Y - %R")%>" id='dateRange' type="text" data-date-picker-target='input' data-action='change->date-picker#processDateChange'>
      </div>

      <%= f.input :start_date, as: :string, wrapper_html: {style: 'display: none'}, input_html: { data: { date_picker_target: 'start'} } %>
      <%= f.input :end_date, as: :string, wrapper_html: {style: 'display: none'}, input_html: { data: { date_picker_target: 'end'} }  %>
    </div>
      <%= f.association :location, collection: Location.pluck(:address, :id) %>
      <%= f.submit "Submit Booking", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="body-page">
<div class="container">
  <h1 class="page-title">New Booking</h1>
  <%= simple_form_for [@car, @booking] do |f| %>
    <div data-controller='date-picker'>

      <div class='mb-3 string required booking_start_date'>
        <label class='form-label string required' for='dateRange'>Select Date</label>
        <input class='form-control string required' id='dateRange' type="text" data-date-picker-target='input' data-action='change->date-picker#processDateChange'>
      </div>

      <%= f.input :start_date, as: :string, wrapper_html: {style: 'display: none'}, input_html: { data: { date_picker_target: 'start'} } %>
      <%= f.input :end_date, as: :string, wrapper_html: {style: 'display: none'}, input_html: { data: { date_picker_target: 'end'} }  %>
    </div>

      <%= f.association :location, collection: Location.pluck(:address, :id)%>
      <%= f.submit "Submit Booking", class: "btn btn-primary" %>
  <% end %>
</div>
</div>

app/views/cars/index.html.erb
<div class="wholepage">
  <div class="heading-container">
    <h1 class="headerone"> Cars Available: <small class="results-count"><%= @cars.length %> Results</small></h1>

  </div>
  <div class="row justify-content-center searchbar">
  <div class="col-sm-8 my-3">
    <%= form_with url: cars_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search" , name: "", class: " btn-fcard" %>
    <% end %>
  </div>
</div>

<div class="row full-car-card">
  <% @cars.each do |car| %>
    <div class="col-md-6">
      <div class="car-card">
        <div class="car-card-body d-flex justify-content-between">
          <!-- Car image column -->
          <div class="col-md-10 car-div d-flex">
            <% if car.photos.first.present? %>
              <%= cl_image_tag car.photos.first.key, alt: "#{car.brand} #{car.model}", width: "300px", height: "300px", class: "car-image " %>
            <% else %>
              <%= image_tag asset_path("img car.png"), alt: "#{car.brand} #{car.model}", class: "car-image img-fluid" %>
            <% end %>
             <div class="description-title">
                <h5 class="car-card-title"><%= "#{car.brand} #{car.model}" %></h5>
                <div class="d-flex">
                  <div class="d-flex">
                    <%= image_tag asset_path("manual-transmission.png"), class: "icsize" %>
                   <p class="ps-2"><%= car.automatic ? "Automatic" : "Manual"%></p>
                  </div>
                  <div class="d-flex ps-3">
                    <%= image_tag asset_path("car-seat.png"), class: "icsize" %>
                    <p class="ps-2 "><%= "#{car.seats}"%></p>
                  </div>
                </div>
              </div>
          </div>
            <!-- Car details column -->
            <div class="col-md-2 d-flex justify-content-end">

              <div class="text-end best-price">
                <p class="vehicle-pricing">BEST PRICE</p>
                <p class="price-text">£<%= "#{car.price_per_day.round} / day" %></p>


                <%= link_to "Select", car_path(car), class: "btn-fcard" %>


              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>






<%# <div class="container">
  <div class="row">
    <%= image_tag "APEXAUTO.png", alt: "Le Wagon", width: 400 %>
  <%# </div> %>
<%# </div> %>

app/views/cars/new.html.erb
<div class="page1">
  <div class="page-wrapper">
    <h1 class="rent-out-header">Rent Out Your SuperCar</h1>

    <%= simple_form_for @car do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group mb-3 g1">
            <label for="brand">Brand</label>
            <%= f.input :brand, placeholder: "Enter car brand", label: false, input_html: { class: "form-control f1", id: "brand" } %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group mb-3 g1">
            <label for="model">Model</label>
            <%= f.input :model, placeholder: "Enter car model", label: false, input_html: { class: "form-control f1", id: "model" } %>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group mb-3 g1">
            <label for="seats">Seats</label>
            <%= f.input :seats, placeholder: "Number of seats", label: false, input_html: { class: "form-control f1", id: "seats" } %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group mb-3 g1">
            <label for="fuelType">Fuel Type</label>
            <%= f.input :fuel_type, collection: ["Petrol", "Diesel", "Electric"], prompt: "Choose...", label: false, input_html: { class: "form-select f1", id: "fuelType" } %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group mb-3 g1">
            <label for="pricePerDay">Price per day</label>
            <%= f.input :price_per_day, placeholder: "Enter price per day", label: false, input_html: { class: "form-control f1", id: "pricePerDay" } %>
          </div>
        </div>
      </div>


      <div class="form-check mb-3 g1">
        <%= f.input :automatic, as: :check_boxes, placeholder: "Number of seats", label: false, input_html: { class: "form-check-input inp", id: "automatic" } %>
      </div>

      <div class="form-check mb-3 g1">
        <%#= label_tag "bluetooth", "Bluetooth", class: "form-check-label fcl" %>
        <%= f.input :bluetooth, as: :check_boxes, label: false, input_html: { class: "form-check-input inp", id: "bluetooth" } %>
      </div>

      <div class="form-group mb-3 g1">
        <label for="color">Color</label>
        <%= f.input :color, placeholder: "Enter car color", label: false, input_html: { class: "form-control f1", id: "color" } %>
      </div>

      <div class="form-group mb-3 g1">
        <label for="photos">Photos</label>
        <%#= file_field_tag "photos[]", multiple: true, class: "form-control f1", id: "photos" %>
        <%= f.input :photos, as: :file, label: false, input_html: { class: "form-control f1", id: "photos", multiple: true } %>
      </div>

      <%= f.submit "Confirm", class: " confirm-btn" %>
    <% end %>
  </div>

</div>

app/views/cars/show.html.erb
<div class="container-fluid py-5 car-background">
    <div id="mainshow-container">
        <div class="text-center  p-5 car-header">
            <%= content_tag :h1, "#{@cars.brand} #{@cars.model}", class: " showheader" %>
            <div id="carouselExample" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @cars.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%= 'active' if index === 0 %>">
                    <div class="d-flex align-items-center justify-content-center w-100">
                      <%= cl_image_tag photo.key, class: "d-block w-50 showimg" %>
                    </div>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <i class="fa-solid fa-chevron-left fa-2xl" style="color: #FF6600;"></i>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <i class="fa-sharp fa-solid fa-chevron-right fa-2xl" style="color: #FF6600;"></i>
                <span class="visually-hidden">Next</span>
              </button>
            </div>

        </div>
        <div class="row justify-content-center align-items-center">
            <div class="bottom-card">
                <div id="box">
                    <div id="show-card-body">
                        <h5 class="showh1"><%= "#{@cars.brand} #{@cars.model}" %></h5>
                        <ul id="carinfo" class="list-group list-group-flush">
                            <li ><i class="bi bi-palette-fill"></i> Color : <%= @cars.color %></li>
                            <li ><i class="bi bi-palette-fill"></i> Bluetooth Supported ? : <%= @cars.bluetooth ? "Yes" : "No" %></li>
                            <li ><i class="bi bi-palette-fill"></i> Transmission : <%= @cars.automatic ? "Automatic" : "Manual" %></li>
                            <li ><i class="bi bi-palette-fill"></i> Seats : <%= @cars.seats %></li>
                            <li ><i class="bi bi-palette-fill"></i> Price / Day : £ <%= @cars.price_per_day %></li>
                            <li ><i class="bi bi-palette-fill"></i> Fuel Type : <%= @cars.fuel_type %></li>
                            <!-- Add more list items here -->
                        </ul>
                        <%= link_to "Go back", cars_path, class: "showbtn" %>
                        <%= link_to "Rent This Car", new_car_booking_path(@cars), class: "showbtn" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApexAuto</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="notice mb-0"><%= notice %></p>
    <p class="alert mb-0"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="background-page">
<h1 class="text-center mb-4 booking-header">Your Bookings</h1> <!-- Added mb-4 class for margin-bottom -->
<div class="row">
  <% @bookings.each do |b| %>
    <div class="col-12 col-lg-4 col-md-6">
      <div class="booking-card">
        <div class="card-content">
          <h5 class="card-name"><%= "#{b.car.brand}  #{b.car.model}" %></h5>
          <p class="card-script">
          <p><%= "From - #{b.start_date.strftime("%m/%d/%Y - %R")} to #{b.end_date.strftime("%m/%d/%Y - %R")}" %></p>
            <p>Total Price £<%= b.car.price_per_day * (b.end_date.to_date - b.start_date.to_date).to_i %></p>
            <p><%=  "Location: #{b.location.address}" %></p>
            <div class="d-flex flex-column align-items-center">
              <div class="d-flex w-50 btn">
                <%= link_to "Edit Booking", edit_booking_path(b) %>
              </div>
              <div class="d-flex w-50 btn">
                <%= link_to "Delete", booking_path(b), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h1 class="text-center mb-4 list-header">Your Listings</h1>
<div class="row">
<% @usercars.each do |car| %>
<div class="col-12 col-lg-4 col-md-6">
 <div class="listing-card">
 <div class="card-content">

 <i class="fa-solid fa-car "></i> <%= "#{car.brand} #{car.model}" %>
 <p><i class="fa-solid fa-money-bill"></i> Total £<%= car.price_per_day %> </p>
 <p><i class="fa-solid fa-paintbrush"></i> <%= car.color %></p>
 <p><i class="fa-solid fa-gear"></i> <%= car.automatic ? "Automatic" : "Manual" %></p>
 <p><i class="fa-brands fa-bluetooth"></i> <%= car.bluetooth ? "Supported" : "Not Supported" %></p>

 <p><i class="fa-solid fa-gas-pump"></i> <%= car.fuel_type %></p>
     </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">

  <div class="homepage">
    <div class="banner" style="background-image: url('<%= asset_path('background.jpg') %>');">
      <div class="home-title">
        <h1 class= "headerone" > Apex Auto </h1>
        <%= link_to "RENT A CAR", cars_path, class: "rent-button" %>
      </div>

    </div>
    <div class="offer-card">
    <p class= "offer">WE OFFER CAR RENTALS</p>
    </div>
    <div class="slogan">
      <h1 class="slogan-text">Your Ultimate Ride Awaits</h1>
      <p class="rental-description">
      Renting a car has never been easier with our two-step process. Simply choose your desired vehicle and pick-up location, then confirm your reservation. With our user-friendly platform and efficient service, you can get on the road in no time, experiencing hassle-free travel tailored to your needs.
      </p>
  </div>
    <h1 class= "headertwo" > Our Services & Branches </h1>

    <div class="card-whole">
      <div class="services-card">
      <h2 class="service-title">Quick Car Rental</h2>
      <p class="services-para">
        Renting a car has never been easier with our two-step process. Simply choose your desired vehicle and pick-up location, then confirm your reservation. With our user-friendly platform and efficient service, you can get on the road in no time.
      </p>
    </div>
    <div class="services-card">
      <h2 class="service-title">Flexible Car Hire</h2>
      <p>
        Our flexible car hire service offers convenient transportation solutions tailored precisely to your needs. Choose from our diverse fleet of vehicles and enjoy the freedom to explore your destination at your own pace.
    </div>
    <div class="services-card">
      <h2 class="service-title">List Your Car </h2>
      <p class="services-para">
        Have a car sitting idle? List it on our platform and start earning extra income by renting it out to travelers. With secure payment processing and comprehensive insurance coverage, listing your car for rent is a safe and reliable way to maximize its value.
      </p>
    </div>
  </div>

  <div class="map" style="width: 80%; height: 520px; margin: 0 auto"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
l

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path("APEXAUTO.png"), alt: "logo", class: "logo"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Rent A Car", cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List Your Car", new_car_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>